# version: '3.8'

services:
  web:
    build: 
    # .은 컨테이너를 만들기 위한 현재 작업디렉토리
      context: .
      dockerfile: Dockerfile

    image: news_web:latest
    container_name: news_web
    restart: always
    
    # 개발중에만 사용 / 배포용으로는 주석처리
    # volumes:
    #   - .:/app
    ports:
      - "8000:8000"
    #위 db랑 의존
    networks:
      - mynetwork
    env_file:
      - .env.prod  
    volumes:
      - static_volume:/app/staticfiles  # 공유 static
      

  nginx:
    image: nginx:latest
    container_name: news_nginx
    #80번 포트는 웹서버 기본이다 .www.naver.com:80 이런식으로 안한다
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/app/staticfiles  # 공유 static
    depends_on:
      - web
    networks:
      - mynetwork

networks:
  mynetwork:

volumes:
  static_volume:  # ✅ Django와 nginx가 공유하는 볼륨