name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 깃허브 저장소에서 최신 코드 가져오기
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. SSH 키 설정
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      # 3. SSH 연결 테스트 (디버깅용)
      - name: Test SSH connection
        run: |
          ssh -o StrictHostKeyChecking=no -v ubuntu@15.164.49.6 "echo 'SSH connection successful'"

      # 4. EC2로 코드 배포 및 도커 컨테이너 재시작
      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@15.164.49.6 << 'EOF'
            cd ~/learning
            git pull origin main
            docker-compose down
            docker-compose up -d --build
          EOF